name: deploy-dev-environment

on:
  push:
    branches:
      - dev
      - add-github-action-deploy

jobs:
  deploy-dev-environment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Make generate-env-file.sh executable
        run: chmod +x scripts/generate-env-file.sh
      - name: Generate .env file
        run: ./scripts/generate-env-file.sh
      - name: Make deploy.sh executable
        run: chmod +x scripts/deploy.sh
      - name: Deploy to Dev Environemnt
        run: |
          ./scripts/deploy.sh "$VPS_USERNAME" "$VPS_HOST" "$SSH_PRIVATE_KEY"
