name: deploy-prod-environment

on:
  push:
    branches:
      - main

jobs:
  deploy-dev-environment:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: SSH and run commands
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
      - name: Make generate-env-file.sh executable
        run: chmod +x scripts/generate-env-file.sh
      - name: Generate .env file
        run: |
          ./scripts/generate-env-file.sh "${{ secrets.JWT_KEY }}" "${{ secrets.GOOGLE_KEY }}" "${{ secrets.DB_PASSWORD }}" "${{ secrets.DB_USER }}" "${{ secrets.DB_URL }}" "${{ secrets.DB_DATATABLE }}" "${{ secrets.EMAIL_SERVER }}" "${{ secrets.EMAIL_USER }}" "${{ secrets.EMAIL_PASSWORD }}"
      - name: Make deploy.sh executable
        run: chmod +x scripts/deploy-prod.sh
      - name: Deploy to Production Environemnt
        run: |
          ./scripts/deploy-prod.sh "${{ secrets.VPS_USERNAME }}" "${{ secrets.VPS_HOST }}" "${{ secrets.SSH_PRIVATE_KEY }}"
