name: deploy-dev-environment

on:
  push:
    branches:
      - dev
      - add-github-action-deploy

jobs:
  deploy-dev-environment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Make generate-env-file.sh executable
        run: chmod +x scripts/generate-env-file.sh
      - name: Generate .env file
        run: ./scripts/generate-env-file.sh
      - name: Make deploy.sh executable
        run: chmod +x scripts/deploy.sh
      - name: SSH and run commands
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy to Dev Environemnt
        run: |
          ./scripts/deploy.sh "${{ secrets.VPS_USERNAME }}" "${{ secrets.VPS_HOST }}" "${{ secrets.SSH_PRIVATE_KEY }}"
