name: deploy-dev-environment

on:
  push:
    branches:
      - dev
      - add-github-action-deploy

jobs:
  deploy-dev-environemnt:
    runs-on: ubuntu-latest
    environement: dev
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Generate .env file
        run: ./scripts/generate-env-file.sh
      - name: Deploy to Dev Environemnt
        run: ./scripts/deploy.sh
